apiVersion: v1
kind: Service
metadata:
  name: istio-gateway-metrics
  namespace: llm-d-pfc-cpu
spec:
  selector:
    gateway.networking.k8s.io/gateway-name: llm-d-inference-gateway
  ports:
  - name: metrics
    port: 15020
    targetPort: 15020
    protocol: TCP
  type: ClusterIP
