apiVersion: v1
data:
  dcgm.url: http://nvidia-dcgm-exporter.nvidia-gpu-operator.svc.cluster.local:9400/metrics
  epp.url: http://llm-d-infpool-epp.llm-d-pfc-cpu.svc.cluster.local:9090/metrics
  istio.url: http://istio-gateway-metrics.llm-d-pfc-cpu.svc.cluster.local:15020/stats/prometheus
  vllm.url: http://vllm-metrics.llm-d-pfc-cpu.svc.cluster.local:8000/metrics
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"dcgm.url":"http://nvidia-dcgm-exporter.nvidia-gpu-operator.svc.cluster.local:9400/metrics","epp.url":"http://llm-d-infpool-epp.llm-d-pfc-cpu.svc.cluster.local:9090/metrics","istio.url":"http://10.128.0.207:15020/stats/prometheus","vllm.url":"http://10.128.0.200:8000/metrics"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"openmetrics-pmda-configmap","namespace":"llm-d-pfc-cpu"}}
  creationTimestamp: "2026-02-11T05:10:27Z"
  name: openmetrics-pmda-configmap
  namespace: llm-d-pfc-cpu
  resourceVersion: "698444"
  uid: 1b700cfc-b8bd-42c6-aa5d-150acf5af04c
