apiVersion: v1
kind: Service
metadata:
  name: vllm-metrics
  namespace: llm-d-pfc-cpu
spec:
  selector:
    llm-d.ai/inference-serving: "true"
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
